### ISSUE TITLE
Add Project - Target Locations Reporter Overwritten by Project Focal Point

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportHub#27]
When I select a reporter, it saves correctly
<img width="956" alt="screen shot 2017-12-20 at 10 29 50 am" src="https://user-images.githubusercontent.com/1784705/34195915-d952c416-e570-11e7-9cb7-37dc40c7ac4c.png">

After that when I save the project or refresh the page, its overwritten by the Project Focal Point
<img width="950" alt="screen shot 2017-12-20 at 10 30 05 am" src="https://user-images.githubusercontent.com/1784705/34195949-ea338d74-e570-11e7-9383-cc758d404998.png">

This needs to be fixed so it works as desired.

**Comment by pfitzpaddy** [comment]
@drfaustusfade It seems like some locations are being overwritten too. If you can register to Ethiopia and make a project with the following Target Locations; 
- Select Oromia -> West Hararge - > Hawi Gudina
- Select Oromia -> West Hararge - > Other

This should result in some funny sort of override - should be related. Thanks

**Comment by drfaustusfade** [comment]
this issue is on the backend, 
on project user update, to keep consistency within a project, related collections to project were updated, including for target locations and location,
as there is per target location reporting, it is not needed for these ones.
updated
https://github.com/pfitzpaddy/ngm-reportEngine/pull/14

**Comment by pfitzpaddy** [comment]
Thanks @drfaustusfade

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD
